FROM maven:3.8.5-openjdk-17-slim

WORKDIR /picpay
COPY . .

# Set environment variables
ENV DATABASE_URL_TEST=$DATABASE_URL_TEST \
    DATABASE_USER_TEST=$DATABASE_USER_TEST \
    DATABASE_PASS_TEST=$DATABASE_PASS_TEST \
    AUTHORIZATION_API_URL=$AUTHORIZATION_API_URL \
    NOTIFICATION_API_URL=$NOTIFICATION_API_URL \
    JWT_SECRET=$JWT_SECRET

RUN mvn clean install

CMD mvn spring-boot:run