version: '3.8'

services:

  api:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/picpay
    env_file:
      - .env
      - .env.test

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .docker/pgadmin:/database/admin/pgadmin
    ports:
      - "5050:80"