version: '3.8'

services:

  api:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/picpay

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - .docker/pgadmin:/database/admin/pgadmin
    ports:
      - "5050:80"